### ISSUE TITLE
test-it\Wait.via is failing intermittently in local and CI runs

### ISSUE THREAD

**Issue by sanmut** [ni/VireoSDK#144]
We have to fix the test or make it a manual one. The following was output in a recent CI failure run.

    UInt8  counter size: 'false'.
        Ticks different: 'false'.

**Comment by spathiwa** [comment]
It’s failing because storing the tick counter in an Int8 causes it to wrap very often, and sometimes the old value and new value being compared are the same because it wrapped.

We should just remove the UInt8 comparison tick count portion of the test.  It is not indicative of a real problem and is not even useful in a manual test.

Craig

**Comment by sanmut** [comment]
@spathiwa fixed it recently.
