### ISSUE TITLE
Add method to set memory limit when engine initialized

### ISSUE THREAD

**Issue by PaulAustin** [ni/VireoSDK#56]
Host context should be able to limit amount of memory allocated during execution of VIA file.

**Comment by rajsite** [comment]
Good to know: https://groups.google.com/d/msg/emscripten-discuss/6Sox46w_TfY/sD96lyE2AgAJ

**Comment by rajsite** [comment]
As of https://github.com/ni/VireoSDK/commit/9d7a85f3094db14ab145267769c75f9266a83817 a Vireo JS user can provide a custom module object and as part of that they can specify [TOTAL_MEMORY](https://github.com/ni/VireoSDK/blob/6aa2d143a4223a723dcc5a72c6b53a7fbb6eb629/test-it/karma/publicapi/VireoConstructor.Test.js#L15) if desired. Custom module objects are not a fully supported use-case and may be removed or change behavior without warning (ie behavior changes as a result of emscripten version change or migration to WASM instead of asm.js).
